run:
  timeout: 5m
  skip-dirs:
    - vendor

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosimple

issues:
  exclude-dirs:
    - vendor
