#!/bin/bash

set -e

if [ -n "$DEBUG" ];then
    set -x
    PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }' # print line number and function name
fi

cd "$(dirname "$0")/.."

mkdir -p bin
bindir="$PWD"/bin

version=$(git rev-parse HEAD)
describe=$(git describe --tags --always --dirty)

go build -o "$bindir/orchestrator" -ldflags "-X main.AppVersion=${version} -X main.BuildDescribe=${describe}" ./go/cmd/orchestrator/main.go

rsync -qa ./resources $bindir/
