#!/bin/bash

set -e

if [ -n "$DEBUG" ];then
    set -x
    PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }' # print line number and function name
fi

cd "$(dirname "$0")/.."

mkdir -p bin
bindir="$PWD"/bin

commit=$(git rev-parse HEAD)
if [ -f RELEASE_VERSION ]; then
  version=$(tr -d '[:space:]' < RELEASE_VERSION)
else
  version=$(git describe --tags --always --dirty)
fi

go build -o "$bindir/orchestrator" -ldflags "-X main.AppVersion=${version} -X main.GitCommit=${commit}" ./go/cmd/orchestrator/main.go

rsync -qa ./resources $bindir/
